BEGIN;

CREATE TABLE IF NOT EXISTS public.tenant_group (
    group_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id uuid NOT NULL REFERENCES public.company(company_id) ON DELETE CASCADE,
    parent_group_id integer REFERENCES public.tenant_group(group_id) ON DELETE SET NULL,
    name character varying(100) NOT NULL,
    code character varying(50) NOT NULL,
    email character varying(255),
    short_name character varying(50),
    description text,
    is_default boolean DEFAULT false NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_tenant_group_company_code UNIQUE (company_id, code),
    CONSTRAINT uq_tenant_group_company_name UNIQUE (company_id, name)
);

ALTER TABLE public.tenant_group
    ADD COLUMN IF NOT EXISTS company_id uuid REFERENCES public.company(company_id) ON DELETE CASCADE;

ALTER TABLE public.tenant_group
    ADD COLUMN IF NOT EXISTS parent_group_id integer REFERENCES public.tenant_group(group_id) ON DELETE SET NULL;

ALTER TABLE public.tenant_group
    ADD COLUMN IF NOT EXISTS name character varying(100);

ALTER TABLE public.tenant_group
    ADD COLUMN IF NOT EXISTS code character varying(50);

ALTER TABLE public.tenant_group
    ADD COLUMN IF NOT EXISTS email character varying(255);

ALTER TABLE public.tenant_group
    ADD COLUMN IF NOT EXISTS short_name character varying(50);

ALTER TABLE public.tenant_group
    ADD COLUMN IF NOT EXISTS description text;

ALTER TABLE public.tenant_group
    ADD COLUMN IF NOT EXISTS is_default boolean DEFAULT false NOT NULL;

ALTER TABLE public.tenant_group
    ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true NOT NULL;

ALTER TABLE public.tenant_group
    ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE public.tenant_group
    ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE public.tenant_group
    DROP CONSTRAINT IF EXISTS uq_tenant_group_group_type_code;

ALTER TABLE public.tenant_group
    DROP CONSTRAINT IF EXISTS uq_tenant_group_group_type_name;

DROP INDEX IF EXISTS public.idx_tenant_group_type;

ALTER TABLE public.tenant_group
    DROP COLUMN IF EXISTS group_type_id CASCADE;

DROP TABLE IF EXISTS public.tenant_group_type CASCADE;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uq_tenant_group_company_code'
    ) THEN
        ALTER TABLE public.tenant_group
            ADD CONSTRAINT uq_tenant_group_company_code UNIQUE (company_id, code);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uq_tenant_group_company_name'
    ) THEN
        ALTER TABLE public.tenant_group
            ADD CONSTRAINT uq_tenant_group_company_name UNIQUE (company_id, name);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_tenant_group_company
    ON public.tenant_group USING btree (company_id);

CREATE INDEX IF NOT EXISTS idx_tenant_group_parent
    ON public.tenant_group USING btree (parent_group_id);

ALTER TABLE public.tenant
    ADD COLUMN IF NOT EXISTS group_id integer REFERENCES public.tenant_group(group_id) ON DELETE SET NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = 'tenant_group_membership'
    ) THEN
        WITH ranked AS (
            SELECT tenant_id,
                   group_id,
                   ROW_NUMBER() OVER (
                       PARTITION BY tenant_id
                       ORDER BY created_at DESC NULLS LAST, membership_id DESC
                   ) AS rn
            FROM public.tenant_group_membership
        )
        UPDATE public.tenant AS tenant
        SET group_id = ranked.group_id
        FROM ranked
        WHERE tenant.tenant_id = ranked.tenant_id
          AND ranked.rn = 1
          AND tenant.group_id IS NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_tenant_group_id
    ON public.tenant USING btree (group_id);

DROP TABLE IF EXISTS public.tenant_group_membership CASCADE;

COMMIT;
